#!/bin/bash

#---------------------------------------------------------------------- #
# admjobs.sh -> given a file with id reads a subs.csv file, submits the #
# calculations to miztli, waits for the calculations done, calculates   #
# the properties and saves the information in a results.csv file.       #
#-----------------------------------------------------------------------#

###---run admjobs.sh creates a directory with the name specified at $HOME
mols_dir=''         #general directory for the molecules
job_dir=''			#job_id as a value passed to the variable job_dir (id generated by gryffin) or
#read -r job_dir < uuidmol	#job_id read from some file saved in the folder created
molecule=''			#molecule type to be calculated (Bpy or Diquat). 
input_file='subs.csv'
#mkdir -p $mols_dir              #*

print_usage() {
  printf "Usage: admjobs.sh [-d mols_dir] [-j job_id] [-m molecule_type]\n"
}

while getopts 'd:j:m:v' flag; do
  case "${flag}" in
    d) mols_dir="${OPTARG}" ;;
    j) job_dir="${OPTARG}" ;;
    m) molecule="${OPTARG}" ;;
    *) print_usage
       exit 1 ;;
  esac
done

shift $(($OPTIND - 1))
echo $job_dir

###---copy from eri to miztli
JobsSubmit(){
read -r fgs < $mols_dir/$job_dir/subs.csv  #*
echo "${job_dir}" > $mols_dir/$job_dir/uuidmol #*
scp -r $mols_dir/$job_dir mflol_a@132.247.177.99:/tmpu/cab_g/mflol_a/$mols_dir #* 
echo "${job_dir}: submitting molecule to miztli at $(date +%F_%T)...
Core: $molecule, Functional Groups: $fgs" >> progress #* 
if [ "$molecule" = "Bpy" ] ; then
   echo "${job_dir} Calculations submitted..."
   ssh mflol_a@132.247.177.99 "cd /tmpu/cab_g/mflol_a/$mols_dir/$job_dir && nohup bash /tmpu/cab_g/mflol_a/Settings-miz/general_bpy.sh &"
elif [ "$molecule" = "Diquat" ] ; then
   echo "${job_dir} Calculations submitted..."
   ssh mflol_a@132.247.177.99 "cd /tmpu/cab_g/mflol_a/$mols_dir/$job_dir && nohup bash /tmpu/cab_g/mflol_a/Settings-miz/general_diquat.sh &"
elif [ "$molecule" = "NAM" ] ; then
   echo "${job_dir} Calculations submitted..."
   ssh mflol_a@132.247.177.99 "cd /tmpu/cab_g/mflol_a/$mols_dir/$job_dir && bash /tmpu/cab_g/mflol_a/Settings-miz/runjobs.sh"
elif [ "$molecule" = "NQ" ] ; then
   echo "${job_dir} Calculations submitted..."
   ssh mflol_a@132.247.177.99 "cd /tmpu/cab_g/mflol_a/$mols_dir/$job_dir && nohup bash /tmpu/cab_g/mflol_a/Settings-miz/general_quinones.sh &"
fi
echo "${job_dir}: molecule submitted to miztli at $(date +%F_%T)" >> progress #* 
sleep 30
}
#JobsSubmit

###---This section waits for the job done
scp -r mflol_a@132.247.177.99:/tmpu/cab_g/mflol_a/$mols_dir/$job_dir/Energy_files $mols_dir/$job_dir #*
scp -r mflol_a@132.247.177.99:/tmpu/cab_g/mflol_a/$mols_dir/$job_dir/Coord_opt $mols_dir/$job_dir    #*

JobsAnalysis() {
energies=`ls $mols_dir/$job_dir | grep -c "Energy_files"`  #*
if [ "$energies" -eq "1" ] ; then
   cd $mols_dir/$job_dir  #*
   echo "${job_dir}: redox potential, pKa, and logS calculation..."
   if [ "$molecule" = "Bpy" ] ; then
      python $HOME/Scripts/Settings-miz/Modules/properties_calc_bpy.py
   elif [ "$molecule" = "Diquat" ] ; then
      python $HOME/Scripts/Settings-miz/Modules/properties_calc_diquat.py
   elif [ "$molecule" = "NAM" ] ; then
      python $HOME/Scripts/Settings-miz/Modules/properties_calc_NAM.py
   elif [ "$molecule" = "NQ" ] ; then
      python $HOME/Scripts/Settings-miz/Modules/properties_calc_NQs.py
   fi
   cd $HOME/Scripts/Settings-miz  #*
   echo "$job_dir: Calculations done! at $(date +%F_%T)" >> progress  #*
else
   echo "$job_dir: Error!, no Energy_file found!" >> progress  #*
fi
}
JobsAnalysis


